import { Typography } from "@mui/material";
import React from "react";

const About = () => {

    const getAbout = () => {
        return (
            <>
                <Typography>Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic cupiditate natus mollitia a sequi excepturi deleniti vel temporibus! Maxime quo et illo consequatur adipisci unde? Voluptatibus, porro ea! Incidunt, eum.
                    Quod nesciunt voluptatibus molestiae sint ab. Rem, accusantium. Obcaecati et consectetur odit maiores repellat tempore voluptates, dolorem tempora. Nulla cupiditate, ducimus labore fugiat repellat odit ipsum facere vitae unde corporis?
                    Modi minus tenetur rem illo deleniti? Laudantium, quas iure. Amet, impedit voluptates laboriosam facere modi rem vitae libero adipisci, eius, hic velit placeat fugiat at repellat saepe facilis nisi dolores.
                    Possimus natus nemo molestias ipsum repellendus culpa voluptas, reiciendis velit corporis, nisi obcaecati. Sunt fugit commodi, inventore earum, provident rerum officiis quibusdam dolores, sit porro distinctio nihil neque minus dignissimos?
                    Amet iusto, suscipit sint, quis in quae dolorem ratione facilis perspiciatis eius voluptatibus, beatae quam adipisci rerum animi dolores nulla enim. Fugiat ipsum molestiae, est debitis quaerat nesciunt dolores neque?
                    Aliquam beatae repellat sed dolorem adipisci dolor ipsum omnis nemo autem ad labore reiciendis error facilis quibusdam natus recusandae eligendi dolorum pariatur debitis, animi tempora! Placeat odit autem modi repellendus!
                    Nam, nostrum, nemo, esse maiores optio tempore dolorum consequatur dignissimos aspernatur ut rem perferendis odio. Temporibus accusantium assumenda veritatis dolores at perferendis odit consectetur rerum illo nesciunt, ullam quibusdam placeat.
                    Asperiores accusantium, officia odit incidunt nemo repudiandae totam deleniti tenetur exercitationem facilis. Consectetur nihil in quasi sint molestias hic doloremque sit placeat dicta, praesentium minus, quibusdam ratione laudantium illum tempore!
                    Obcaecati aperiam sed, maxime rerum atque voluptatum corporis illo quibusdam, cum ullam ratione animi ut eius, libero veritatis similique. Dicta numquam magni voluptates consectetur pariatur! Minima neque impedit dignissimos id.
                    Tenetur porro, nam distinctio dignissimos cumque reprehenderit odit voluptatibus molestiae nesciunt sit saepe voluptate ratione nihil, laudantium rem id dolores labore neque quae modi illum fugit possimus vitae? Sequi, aperiam.
                    Accusantium tempore voluptates et? Blanditiis repellat officiis unde esse laudantium quisquam voluptatibus reprehenderit ut temporibus assumenda provident, architecto illum at aliquid nesciunt saepe quae exercitationem numquam. Cumque deleniti possimus voluptas.
                    Aliquid iusto asperiores ad aut, animi odio amet totam! Blanditiis distinctio facilis aut quae deserunt ducimus maxime officia sint, ipsam voluptas itaque esse laborum aliquid doloremque dolores, exercitationem numquam quasi!
                    Perspiciatis fuga, iure aliquam dignissimos voluptate impedit totam itaque quos eos suscipit aut. Reiciendis sequi, necessitatibus architecto nam quia veritatis eligendi sed laboriosam distinctio iste consequuntur illum, suscipit maxime quisquam.
                    Non veniam provident distinctio enim sed nihil. Velit labore illum porro suscipit minus nobis, minima, exercitationem doloremque rerum molestiae natus qui! Nobis esse ad eius magnam adipisci iusto debitis blanditiis.
                    Accusamus pariatur, numquam tempore non nihil iure voluptatibus veniam quia eligendi obcaecati qui sed repudiandae harum, itaque sint, facere enim doloremque odit tempora minus aut! Labore non laborum in vel!
                    Animi obcaecati, modi dolore et reiciendis velit corporis magnam alias quibusdam, error voluptatibus. Aliquid laborum nihil delectus animi officia illum odio laboriosam! Magnam totam dolor reprehenderit sed dolorum, voluptatem animi!
                    Id ipsum tempore quod officiis reiciendis, laboriosam maiores numquam. Eligendi est odio delectus veritatis? Inventore nemo qui nobis dolore odit architecto fugit beatae distinctio laborum. Cupiditate commodi amet harum cumque?
                    Fugit iusto magnam magni blanditiis eligendi at error, corrupti perspiciatis necessitatibus aliquam in placeat illum cum quisquam, aliquid soluta quasi animi sequi eum aut quo laudantium tempore! Commodi, ex exercitationem.
                    Voluptatem accusantium adipisci officiis eveniet, ea laborum fugit aliquid consequuntur iusto vel, obcaecati possimus, vitae atque? Laborum nihil quia modi nisi molestiae ipsam! Dolore repudiandae obcaecati iusto impedit! Obcaecati, magnam.
                    Necessitatibus quae autem accusamus ratione tempora quo labore est? Magnam ab quas impedit reprehenderit quibusdam eum, animi obcaecati ratione corrupti mollitia eaque rem nesciunt velit veniam, odio atque, aliquam minus.
                    Praesentium nihil atque id dignissimos debitis est tempora omnis quae enim repudiandae repellat natus, fuga expedita voluptates rem laborum obcaecati nobis maiores distinctio aut saepe eligendi odio? Cum, molestias similique.
                    Sed natus quas voluptatibus corporis fugiat dolores recusandae aliquid dolore, enim, at doloribus nemo repellendus hic voluptatum consectetur quam laudantium. Id asperiores necessitatibus, dicta accusamus temporibus quasi non! Ducimus, repellat!
                    Quia officiis iure, ab quos hic animi labore fugit porro tempore itaque sint. Explicabo, possimus ratione exercitationem, velit libero, ipsum facilis recusandae rerum sequi ex modi necessitatibus labore excepturi praesentium.
                    Iure provident repudiandae fugit rerum eligendi obcaecati qui! Reprehenderit repellendus accusantium rerum recusandae dolor quas, repudiandae veniam delectus, molestias quae ipsa blanditiis! Nesciunt ratione cum, perferendis modi odio laboriosam nulla.
                    Repellendus, enim. Illum, cumque delectus aliquid id cupiditate quo suscipit voluptatibus dolore repellendus nam magni, obcaecati omnis velit quibusdam molestias blanditiis veniam sed rem tenetur repellat sunt esse, numquam amet.
                    Aspernatur delectus, aut eos nihil illum, quos vero laborum cupiditate quas aperiam modi. Ipsam dignissimos aliquam, necessitatibus alias eum labore, suscipit blanditiis esse accusamus praesentium nemo eos quasi. Nemo, dolore?
                    Aperiam quisquam itaque, aspernatur, amet fugiat ipsa totam deserunt ipsum vitae facilis libero sequi, voluptatem dignissimos qui officia accusamus odit. Voluptate commodi, quia culpa sunt debitis blanditiis cumque doloremque porro.
                    Voluptatem, dolorem eaque tempora a quis ducimus ipsam, repudiandae error molestiae non inventore dolorum soluta adipisci culpa enim aliquam accusantium eos assumenda quibusdam. Laborum, molestiae libero quidem deserunt assumenda suscipit.
                    Ipsam atque aperiam aut maxime suscipit necessitatibus temporibus vel, eaque fuga hic delectus reprehenderit qui voluptate, alias earum perferendis illo quas nulla tempora dignissimos accusantium natus cum vitae molestias. Laudantium.
                    Possimus harum, perferendis officia odit voluptatem esse repellat est eveniet laboriosam exercitationem repellendus maxime iusto consequuntur voluptate velit illum, quis pariatur sint nemo iure. Obcaecati quisquam vel sapiente est quae.
                    Odit illo ullam reprehenderit corrupti ipsam dolorum corporis optio commodi iusto similique nobis odio ad nihil saepe aliquid atque, tempore est id officiis perspiciatis nesciunt fugiat reiciendis voluptatum. Expedita, placeat.
                    Praesentium ipsum, alias sunt, harum eaque corporis veritatis nulla totam commodi sequi provident. Incidunt voluptatibus possimus ut iure quam, exercitationem harum dignissimos dicta odio autem eius nisi architecto perspiciatis earum.
                    Consequuntur alias itaque sed non ipsum veritatis nam sint! Ipsum esse omnis obcaecati ut modi dolor harum nulla vel velit architecto, voluptatibus ab tempore eum rerum necessitatibus voluptate, deleniti tempora!
                    Labore beatae fuga illo delectus, accusamus dolorum facere, blanditiis accusantium consequatur voluptatem, excepturi commodi ullam. Laudantium nobis, cumque doloremque corrupti dolore eaque vero tempora, aliquid a at molestiae provident tempore?
                    Deserunt vitae soluta nihil? Minima hic officiis rem modi ipsam delectus architecto dolorum ipsa numquam earum laboriosam facilis sunt quos corrupti exercitationem, inventore voluptatum. Quam laborum exercitationem labore dolore aspernatur!
                    Labore et nulla aliquam mollitia natus architecto nisi laborum rerum in sunt aperiam soluta beatae eius voluptates est id, sed hic unde quisquam eos voluptate reiciendis ad. Repellendus, omnis odit.
                    Cupiditate minus recusandae vel id ab saepe? Facilis nihil quod amet molestias nostrum accusamus. In labore quibusdam sed ea! Cum sed dolorem sunt obcaecati nesciunt repellendus porro aut nisi voluptatem?
                    Beatae in odio repudiandae error similique rem, non quas atque explicabo? Distinctio veniam labore omnis similique id non. Aspernatur officiis voluptatem hic nobis, obcaecati quas consequuntur culpa commodi iusto earum.
                    Sed laudantium, quae quisquam incidunt vitae voluptate illum voluptates maxime velit in placeat repellendus similique eveniet excepturi libero omnis eius. Harum perspiciatis, recusandae saepe nulla porro ducimus suscipit eaque aliquam?
                    Amet omnis distinctio ratione, ducimus quo debitis vel, obcaecati qui atque illum ex in. Dignissimos voluptatum iste eveniet quibusdam ipsum eius quaerat fuga eum, sit, dolorum explicabo hic doloremque inventore.
                    Repellat suscipit sit, quaerat culpa consequatur in recusandae voluptatibus magnam eos fugit molestias ipsa deserunt illum. Veniam magnam quae hic aliquam possimus, officiis odit illum tempora impedit aspernatur beatae amet?
                    Cumque vel quis, excepturi at eos omnis animi harum quisquam voluptatem veniam tenetur libero nobis neque facilis perspiciatis nemo iure ut voluptatum sit? Eligendi quae voluptatem quos maiores praesentium iste.
                    Asperiores totam, voluptatum debitis rem quibusdam dolor similique modi aperiam dolorum. Ut pariatur molestiae ad iusto nostrum magni numquam soluta! Illo officia deleniti nihil sed optio nulla aperiam accusamus iure.
                    Optio beatae porro expedita consectetur sed aspernatur deleniti corrupti esse illo quae. Assumenda autem recusandae aperiam id, doloribus sequi error dolores minus accusamus natus amet omnis aspernatur hic, nobis itaque!
                    Fugiat blanditiis enim deleniti commodi porro tenetur, veritatis molestias, quia consequatur officiis incidunt, nulla voluptatibus distinctio quis. Harum, natus adipisci, debitis repellendus aliquam voluptate dolore quis sit ea sequi iste.
                    Fugiat cupiditate nesciunt, consectetur consequuntur quidem nulla unde nemo placeat est debitis atque ullam inventore ipsum praesentium pariatur! Fugiat commodi cum deserunt voluptatibus at! Quod consequatur voluptatibus ipsum placeat animi!
                    Alias tenetur ex aliquid expedita id quis molestiae cum tempore placeat quos, vel numquam? Eligendi reiciendis maiores animi tenetur illum. Quas ullam alias, dicta esse ipsum consectetur itaque obcaecati blanditiis!
                    Amet, tempora rerum. Ratione voluptas dicta itaque. Veritatis esse nam sed quam et modi, animi similique praesentium sequi quaerat dolorem, enim, vero blanditiis dolorum. Tenetur dolorum labore iure velit molestiae.
                    Voluptatum error numquam nesciunt iste sed. Voluptatibus magni fugit debitis similique minima exercitationem consequuntur vero aut voluptatum, ipsam voluptatem consectetur totam ducimus? Sint non molestiae placeat, nulla quasi voluptas maxime?
                    Enim aliquam, accusantium sint dicta optio quas iure nisi sequi, repellat impedit explicabo? Modi quo accusamus ea debitis dolore? Exercitationem iure aliquid eveniet accusantium rem sit tempore, omnis non! Quaerat.
                    In ratione rerum nihil perspiciatis quia dolores sed distinctio, voluptas consequuntur itaque eos similique. Aperiam dignissimos alias dolor consectetur commodi eaque, itaque vero accusamus nemo consequatur illo corporis quis nisi.
                    Quo, id provident quisquam vel porro dolor sapiente culpa et beatae asperiores non velit iusto minus qui quod optio. Adipisci aliquam laudantium iusto veritatis eligendi nulla rem obcaecati dolore impedit.
                    Voluptatem aut minus placeat suscipit? Adipisci commodi maxime minima quae numquam reiciendis facilis modi corrupti laboriosam ipsa maiores obcaecati officia doloribus molestiae ducimus unde vel voluptatum ex, repellendus consectetur ipsam?
                    Nesciunt aliquid quod fugiat quos ipsum quis in aspernatur quo delectus suscipit! Eligendi illum est provident modi at accusantium dolores eum ab ipsum. Quis pariatur nulla nam laborum recusandae! Laborum.
                    Voluptates obcaecati cum autem quam neque doloribus dolor nostrum maiores molestias quisquam aut rem eum unde explicabo optio totam, laboriosam est asperiores? Explicabo voluptatum neque non dolorem accusantium quasi soluta!
                    Dolore sit veritatis magnam non dolor aliquam quos nulla, minus iste porro rerum officia, optio magni excepturi ipsam nobis accusantium hic voluptas alias? Minima maxime illo, eos sequi porro tempore.
                    Magni sunt perspiciatis, amet corrupti, ipsa deleniti eligendi facilis hic molestias alias neque consequatur exercitationem pariatur, possimus cumque officiis fugit quibusdam. Fugiat, debitis suscipit. Iure magnam at quae quam suscipit!
                    In natus tempore saepe at nemo repudiandae! Optio qui necessitatibus recusandae temporibus, aliquid laborum non cum pariatur quibusdam libero quam dicta sequi ut atque vitae harum. Dolor expedita aspernatur beatae.
                    Error voluptate esse harum tempore quasi eos, a velit nobis quae deserunt maiores consequuntur maxime aspernatur? Laboriosam tenetur odit velit ex delectus quia. Consectetur officia velit autem placeat beatae vel!
                    Iusto, adipisci dolores. Esse accusantium repellendus illum iure sapiente fugit incidunt facilis quam explicabo adipisci, eos dolorum? Odio, nostrum. Saepe laborum velit asperiores aspernatur alias rem. Excepturi necessitatibus eum magnam?
                    Sequi ipsam voluptates iure ut natus ex quibusdam magni dolorum commodi debitis a at dignissimos dolores, error hic molestiae explicabo incidunt alias laudantium ratione quae. Odio ducimus dolorum voluptatem enim!
                    Aliquam, odit modi deserunt nesciunt quia tenetur earum minus unde recusandae, quibusdam perferendis in assumenda. Dolores nulla, facere vero ipsa libero perspiciatis fugit quas, a numquam placeat, esse voluptatum soluta!
                    Nisi dolor et, labore in iure distinctio, mollitia non ea inventore assumenda eos harum quibusdam ratione quo vero facilis veniam quasi nostrum? Beatae optio nobis dignissimos ut alias molestiae rerum!
                    Minus impedit provident reprehenderit vero, quis facilis omnis odit pariatur laboriosam id suscipit repellendus velit sunt tempora sequi et ab amet molestias vel totam non adipisci voluptas doloribus. Iste, vero!
                    Unde quia quasi expedita hic aperiam? Fugit quas cumque vel debitis molestiae in itaque, odio iusto accusantium, laborum vero veritatis quam. Nihil qui rem assumenda tempore! Veritatis odit eum necessitatibus.
                    Tempore deserunt at sit. Excepturi laboriosam a consectetur, alias molestiae voluptatem voluptate deleniti animi nam soluta iusto quas minima itaque error, nemo perspiciatis mollitia, quasi doloremque eveniet dolorem porro! Ullam.
                    Quia autem dicta cumque! Sed vero eveniet quos nam veniam, nulla aliquam voluptates inventore eos alias provident minima amet consequatur et optio officia ullam! Dignissimos libero qui esse ratione earum?
                    Est, ratione nisi explicabo sed tempora libero aliquid reiciendis animi. Nostrum maxime quo natus, odit, debitis repudiandae labore fuga, iste culpa ex necessitatibus eum quidem qui officiis blanditiis repellendus id!
                    Quas delectus impedit minima unde ducimus! Veritatis sunt ipsum delectus minima ipsam exercitationem! Ullam amet maxime nobis quo earum voluptate quisquam nam nisi rem adipisci cumque quas, pariatur facere maiores!
                    Incidunt esse impedit doloremque maiores possimus nihil voluptas adipisci sunt. Fugiat repudiandae delectus facilis deserunt quas, sed eligendi nulla vero aperiam maxime ipsum doloribus unde odio fuga, nihil fugit error?
                    Quis nulla pariatur, odit dolores accusantium ut quod ratione corporis non est recusandae quia ad perferendis laudantium repudiandae reprehenderit, illo quaerat consequuntur unde tenetur itaque earum illum vel. Ab, eaque!
                    Atque earum rerum doloremque repellendus, distinctio repellat adipisci delectus quae quibusdam id tenetur iusto officia ducimus veniam omnis? Ducimus, dolore qui ab magnam ex quos reprehenderit nesciunt deleniti ipsum quibusdam.
                    Quaerat a excepturi esse nihil ducimus totam sit rem veniam? Sint deleniti est corporis voluptatem beatae, aspernatur, odit commodi suscipit dolore eaque aperiam at esse quidem soluta excepturi? Blanditiis, quos?
                    Temporibus rem ipsum ipsa cupiditate necessitatibus fuga veniam tenetur eveniet quis animi accusantium pariatur maiores est ad neque illum dolore, earum sint harum minima nobis atque. Laudantium, nesciunt? Aliquid, deserunt.
                    Quis inventore amet odio ducimus placeat necessitatibus, maiores at quos rem autem aliquam sit natus, perspiciatis totam dicta qui eum temporibus alias sed exercitationem numquam unde ad aspernatur? Inventore, quos?
                    Maxime dolorem mollitia minima quo voluptate. Quod, quasi qui esse, laboriosam exercitationem sunt quam quibusdam deleniti provident, ipsum molestiae repudiandae ullam sit. Aspernatur libero, necessitatibus minima non vel recusandae quos.
                    Fugit laboriosam nisi quia doloremque explicabo dolor excepturi placeat? Quo recusandae amet asperiores aspernatur tempore suscipit voluptates eveniet, non incidunt at cupiditate excepturi? Dicta eum est eveniet ullam sint eius.
                    Architecto cupiditate pariatur velit expedita soluta vel deserunt commodi iure sequi distinctio, tempore assumenda odio quia beatae consectetur quo ad earum. Libero voluptate at temporibus, explicabo debitis deserunt doloribus placeat.
                    Laudantium corrupti laboriosam numquam vero adipisci necessitatibus quas, illo repellat impedit ea repudiandae aut possimus. A praesentium facilis ipsum iusto fuga laudantium officia non odit temporibus, sunt amet placeat minima.
                    Quidem eaque sequi minima tenetur ab nemo, sed asperiores quae adipisci iusto! Facilis, dolorem voluptatem repudiandae aliquid, dolorum harum esse voluptas perferendis tenetur assumenda incidunt illum id magnam laudantium voluptates.
                    Culpa, aspernatur enim unde accusantium earum itaque. Voluptatibus voluptatum adipisci autem laudantium sit ullam pariatur sed facilis est expedita, repudiandae id officiis dignissimos quae? Ipsa fugit consequatur asperiores amet neque.
                    Autem totam modi dolorem, natus rerum quasi fuga molestias minima id velit unde eum recusandae illo vero ut neque reiciendis eius laboriosam esse. Placeat dolorum minus eligendi modi nostrum natus.
                    In hic explicabo non sint nulla aperiam ad eum, dolorum, harum ipsam minima repellat culpa porro aliquam rerum at qui reiciendis quasi dicta commodi vero facilis quisquam fuga nam? Possimus!
                    Sequi rem non ullam fugit cum vel, dolorum vero quae veniam, qui officia incidunt dignissimos reprehenderit libero nobis quibusdam veritatis ut nulla quia, inventore ipsam molestias necessitatibus! Assumenda, labore deserunt!
                    Quibusdam voluptatem magni dolorem a. Praesentium quod perspiciatis recusandae, ex excepturi, dolore, voluptatem at assumenda corporis sunt inventore soluta nisi accusamus? Nihil, natus tempore. Recusandae molestias quidem itaque laborum mollitia.
                    Earum optio, amet temporibus libero fugiat at ipsum facere odio numquam ipsam totam aspernatur animi doloribus tenetur nihil! Explicabo laudantium rerum aliquid amet praesentium excepturi quos a voluptate recusandae nemo?
                    Dicta assumenda debitis tempora vitae quia impedit enim aut, temporibus ad iste, sapiente animi voluptate neque reiciendis numquam soluta, similique reprehenderit officiis! Repellendus nihil nemo porro magnam harum. Omnis, laboriosam.
                    Blanditiis sit modi magnam nisi unde inventore dolore facilis ipsum expedita amet eligendi incidunt, mollitia magni, quia delectus odio doloremque in velit! Quisquam eos a corporis saepe aperiam, iste nobis.
                    Animi est iusto, alias obcaecati quas harum! Dolorum sunt necessitatibus cum, odit fugiat id sed fuga impedit rem officiis harum officia reiciendis ratione quod, quisquam quia neque quidem a. Atque?
                    Natus iste illum magnam dignissimos adipisci fuga voluptates non dolorum veniam veritatis odio, voluptate, aut officiis laudantium quasi eius asperiores neque quas alias tempora. Quia eveniet natus in voluptatem odit.
                    Architecto commodi deserunt iure aliquid facere voluptate enim blanditiis ullam quae ducimus odit, ipsum dolorum deleniti voluptates similique laborum nostrum facilis! Dolorem corporis unde quaerat error odit, quasi vel! Assumenda.
                    Voluptates nesciunt facere fuga ad neque qui culpa, iure quae, odio at saepe quis modi? Quo odit molestiae nihil asperiores sunt. Quos omnis possimus doloremque expedita voluptatibus est nostrum sequi?
                    Perspiciatis facilis accusantium, dolor minima doloribus nostrum dolore nisi maxime tenetur consequuntur molestiae, doloremque expedita quo quibusdam molestias adipisci, sunt nulla magnam soluta voluptatem odio ad? Quasi aspernatur recusandae magnam!
                    Minus aliquam voluptatibus, veritatis modi dolorem asperiores veniam quisquam ad! Illo ducimus expedita voluptatem delectus voluptatum fugit rem neque. Nemo iure tempora magnam eum nisi perspiciatis sint quibusdam, consequatur temporibus!
                    Esse sit vitae ipsam earum! Aliquam ipsam odio pariatur doloremque architecto, consequuntur aut dolorum officiis similique vel illum atque vitae ducimus! Totam at quod quaerat ut praesentium, facilis nulla officiis.
                    Voluptatibus dolorem optio quas non sequi obcaecati cumque, laboriosam nihil a debitis neque odio quisquam veniam eaque numquam repellat itaque doloremque dolores commodi officiis molestiae autem ipsum, tenetur amet? Quo!
                    Officiis eaque, ab fugit distinctio fuga quis adipisci nam tempore dolorum non deleniti dolore quisquam provident consequatur harum dolor repudiandae similique ullam consequuntur. Reprehenderit quae id nihil! Corporis, molestiae nostrum!
                    Ratione, debitis. Iure, sequi laboriosam voluptates a consectetur aspernatur laborum rem cupiditate repellat non, nesciunt nisi consequuntur, magni dolorem possimus. Minima enim vero sit, doloribus soluta atque consequatur mollitia deserunt.
                    Iure vel blanditiis ea? Vero molestias harum tenetur ipsa asperiores natus quas voluptatem, ipsam numquam! Enim, asperiores laudantium sapiente aut ipsum ullam quae minus quod praesentium eum eius animi non.
                    Excepturi blanditiis ab voluptates alias minima soluta quaerat eos optio molestias assumenda, eum ratione quis adipisci recusandae atque sed dolorem nobis deleniti explicabo accusamus dolore, ut reprehenderit hic! Architecto, cumque!</Typography>
            </>
        )
    }
    return getAbout();
}
export default React.memo(About);