import { Typography } from "@mui/material";
import React from "react";

const Service = () => {
    const getServices = () => {
        return (
            <>
                <Typography>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos doloribus temporibus laboriosam iste ea aperiam ipsam totam veritatis asperiores reprehenderit maiores neque eaque aliquid, accusantium officiis at, quos labore odio!
                    Consequatur ipsa excepturi perspiciatis deleniti labore nostrum aspernatur nam placeat sit exercitationem commodi corporis a omnis quis facilis, dolor blanditiis optio eveniet ullam voluptates veniam? Fugiat minima numquam rerum libero.
                    Alias saepe et at voluptates? Sequi nam consequuntur qui quasi aliquid exercitationem est aut quis laudantium. Quaerat consectetur, architecto labore qui consequatur rem, modi repellendus eos, inventore necessitatibus hic a?
                    Earum quod molestias pariatur dolorem vitae autem dolorum ut nisi maxime officia temporibus rerum veniam iusto eligendi fugiat in reiciendis, tenetur quae voluptatem culpa ad nulla? Assumenda non dolore nobis.
                    Atque, illum nobis obcaecati nam numquam ad nisi vel ratione! Aliquam temporibus, deleniti velit fugiat beatae magnam dolorum, sit officia eius ad illum blanditiis sapiente asperiores id placeat. Eveniet, magni?
                    Ullam nisi doloribus, commodi, neque numquam facilis sint dolorem veniam amet asperiores minima maxime. Ipsa, praesentium, deleniti quis, natus ipsum voluptatibus laborum quisquam maiores quaerat nemo dolorum provident harum. Minima!
                    Possimus vel nulla eos expedita, maxime consequuntur ipsum sint magnam dolorem praesentium, quasi esse ex itaque id porro obcaecati labore accusamus minima consequatur voluptatem. Nisi corporis minus blanditiis beatae iure?
                    Temporibus autem ipsam fuga voluptatibus amet incidunt explicabo dolorum voluptatum sapiente quia, mollitia labore delectus repellat odio iste dolorem doloribus pariatur earum. Facilis ea cumque provident iure eos. Eveniet, fuga.
                    Molestias recusandae voluptatem cumque architecto ea nihil qui enim hic, quas atque earum dolor ipsam. Error ex magnam ad, blanditiis eaque itaque, perspiciatis deleniti nesciunt, tempora est culpa! Eum, consequuntur!
                    Sit hic cupiditate, ab molestiae quidem consectetur accusantium veniam, deleniti error, exercitationem modi eum aut fuga magnam aliquam blanditiis aspernatur facere corrupti commodi voluptate quod sapiente ullam! Itaque, assumenda quidem.
                    Facere rerum doloribus aliquid dolor tempore necessitatibus numquam ipsam vitae? Fugiat rem inventore, dolore maiores beatae libero voluptas est quibusdam dolorem suscipit voluptatum debitis praesentium ut aliquam labore molestiae modi!
                    Quis aut earum porro temporibus obcaecati inventore, illo fuga commodi blanditiis rerum ab dignissimos ducimus natus tenetur sint, eos error labore sapiente beatae repudiandae! Voluptas consequuntur necessitatibus voluptatem minus consectetur?
                    Eos velit illo veritatis nesciunt fuga a eius quaerat quae quam nisi nobis obcaecati assumenda possimus, quod sit aspernatur autem! Quis alias vitae eveniet dolorem ab, odio et pariatur voluptas!
                    Numquam dignissimos autem nemo tempore assumenda dolore sequi repellendus culpa? Officia voluptates pariatur optio voluptate eligendi impedit, consequatur, odit obcaecati libero a vitae earum est. Voluptatum labore sed pariatur doloribus.
                    Earum temporibus eveniet quod labore deserunt officia libero dolor, autem sed obcaecati necessitatibus quibusdam consectetur tempore inventore nam iste! Iure aliquid illum cum eaque officiis corrupti voluptatem rem modi rerum.
                    Modi doloribus laboriosam adipisci perspiciatis sint optio impedit, at voluptatem ab? Velit illo necessitatibus iste, explicabo facere qui est, ratione vero culpa, nulla voluptatem mollitia veniam accusantium omnis repudiandae unde.
                    Ut praesentium dolorem nostrum accusantium laudantium eius commodi quos iusto reprehenderit dolorum! Corrupti, molestiae eligendi. Porro minus corporis repellendus vero dicta unde molestiae dignissimos, exercitationem dolores nobis deserunt numquam praesentium?
                    Suscipit cupiditate ipsum accusamus dolorem doloribus necessitatibus aliquid fugit autem ab similique, exercitationem incidunt molestias at amet repellendus iure voluptatibus ad sequi saepe laudantium non beatae quasi. Molestias, unde magni?
                    Nihil tempora dolorem, maiores veritatis dolor consectetur voluptates velit odit quibusdam doloribus aperiam libero totam quos, porro optio ea repellendus enim magnam. Dolor dolore amet architecto alias exercitationem? Asperiores, facilis!
                    Quos ipsam facilis illum autem vel rerum distinctio provident error blanditiis temporibus officiis natus quaerat delectus, possimus molestiae, reprehenderit asperiores impedit quia ratione? Numquam deleniti debitis, voluptas aliquam culpa illo?
                    Provident similique error ullam, distinctio illum debitis fugit doloremque eos eum sed ea cum et quos omnis expedita nam officia ipsam vitae ipsa amet architecto quas eligendi! Quos, consequuntur quis.
                    Ipsam ullam expedita soluta minima, quam dolore quas nobis ad, deserunt nihil tempora sequi corrupti necessitatibus repellat rem ab laudantium non assumenda? Quaerat asperiores maxime, veritatis ullam cum voluptatibus eius.
                    Iusto esse magni alias sapiente earum quaerat totam suscipit officia deserunt itaque. Illo accusamus veritatis quis, voluptas nobis officiis minima enim excepturi autem labore pariatur fuga, eos quam vitae assumenda?
                    Aspernatur harum eius qui mollitia dignissimos laudantium ab debitis sint maxime explicabo! Impedit maiores cumque ab excepturi. Laudantium fugit molestias quisquam, blanditiis suscipit inventore illum qui nostrum quis, iure exercitationem.
                    Velit consequatur distinctio, dolorum iusto tenetur voluptatem repudiandae? Consequatur magnam at fuga? Veniam exercitationem architecto dolorem vitae quisquam fuga quidem porro labore molestiae eius, nostrum reprehenderit fugiat, illum aut officiis.
                    Qui sequi dolorem facere iure reiciendis possimus eaque perferendis! Explicabo similique libero repellat doloribus impedit nihil sit expedita aut excepturi doloremque voluptatum vel quia minima, dolorum a assumenda amet ex?
                    Amet officia necessitatibus aut vitae inventore similique dicta reiciendis voluptate corrupti. Nisi laudantium eum fugit minus ipsa eius, nemo architecto animi dolore, temporibus adipisci voluptates! Sequi incidunt iusto rem doloribus!
                    Est esse repellat officia, ratione eligendi suscipit error qui debitis vero ipsam veniam enim maxime unde nihil sint a, beatae assumenda sit eos voluptatum cumque quisquam, exercitationem explicabo fugit. Possimus.
                    Modi voluptates repellat voluptate maiores tempora eaque excepturi et, natus provident unde laboriosam amet quae, commodi ex quis iusto! Libero neque in distinctio facilis aspernatur optio ullam mollitia excepturi magnam!
                    Voluptate dolorem vero sit beatae inventore hic quibusdam quis. Blanditiis, magnam tenetur, dolores ad deleniti rem earum harum possimus asperiores repudiandae voluptas itaque, ipsa quam expedita repellendus laudantium magni excepturi?
                    Autem quas reiciendis nihil sint doloribus repudiandae. Quisquam iusto, mollitia eveniet id ratione commodi impedit doloremque, maxime possimus voluptate autem aliquid aut sed eum corporis? Distinctio id impedit asperiores minima.
                    Deserunt quas repudiandae veritatis? Delectus placeat accusamus qui dolor deserunt provident repellat asperiores similique ipsam laborum aut, officia dolorum, aperiam sint quis et? Quae id magni maxime dicta tenetur? Quibusdam?
                    Architecto vitae corrupti ex aliquam nesciunt fugiat est? Odit, totam consequatur est eos sint consequuntur mollitia perspiciatis inventore incidunt, modi praesentium repellat et accusamus distinctio facere similique consectetur rerum culpa.
                    Deleniti minus eaque earum dolores debitis dignissimos eligendi illo velit recusandae fuga, excepturi quia, eum quibusdam molestias quo magnam? Repudiandae nihil aliquam saepe dolorum possimus vitae quam blanditiis doloremque quidem?
                    Officia provident aperiam, odit tempora recusandae, doloremque dicta enim, ea distinctio temporibus vel. Adipisci sit laborum qui id voluptates ullam reiciendis eligendi! Suscipit reprehenderit, quisquam vel dignissimos magnam aut quam.
                    Ut vel id illum tempore reprehenderit hic animi nobis eaque, fugiat omnis aliquam, cum reiciendis quibusdam ex. Quidem quia, distinctio veniam necessitatibus esse laudantium, quod nobis dicta, praesentium ipsum debitis.
                    Adipisci commodi corporis modi, quibusdam soluta asperiores labore? Error, qui rerum blanditiis voluptatibus, dignissimos minus eligendi consectetur accusantium nemo tempore, culpa nostrum obcaecati ut numquam odit ea. Mollitia, quisquam ipsam.
                    Doloribus illum nostrum, perspiciatis dicta labore autem similique quasi beatae quis provident pariatur omnis illo iusto voluptates dolorem officiis? Ipsam maxime laboriosam voluptates esse commodi molestias id. Aliquid, quia recusandae?
                    Perferendis non dolor omnis quaerat facilis, voluptate, eum at nam ipsam quidem possimus neque unde quas nisi ex, placeat iure repellat? Labore earum, dolorum quasi dolore animi saepe voluptatum inventore.
                    Atque commodi vitae maxime laborum sint quod iusto corporis animi! Omnis perferendis, blanditiis a minima maxime quaerat dicta libero repellendus unde, tenetur ipsum amet impedit non, cumque deserunt adipisci dolore.
                    Saepe provident laborum, quibusdam ducimus accusamus ipsum. Numquam labore ad amet doloremque sed voluptatibus minima, quisquam dolorem quibusdam, esse ut dolor, sapiente fuga aliquid maiores adipisci officia reiciendis distinctio praesentium.
                    Fugit, quia soluta. Perferendis rerum nam in commodi, eveniet accusamus voluptatibus aperiam dignissimos autem ullam quo provident sapiente odio vero dolorum nesciunt repudiandae esse. Aperiam molestias unde pariatur! Quisquam, voluptatum!
                    Voluptatibus nemo, animi, exercitationem nesciunt hic reiciendis voluptate numquam quam expedita nobis obcaecati impedit voluptas atque sit quibusdam dignissimos eius ipsa optio eos perferendis quos veniam quaerat iusto totam? Voluptatum.
                    Odit consequatur sit quam nulla, voluptatem suscipit laudantium harum impedit quo eaque saepe voluptatum iste quos consectetur quaerat pariatur quibusdam perspiciatis, voluptate magni! Deleniti modi totam porro dicta architecto animi?
                    Commodi, esse eaque reiciendis quam adipisci quasi aperiam voluptatem eum illo dolore, suscipit atque ipsum ea voluptatibus neque quis! Impedit eum perspiciatis praesentium, enim libero itaque distinctio quasi repellendus id!
                    Sint tempora similique eligendi dolorem sunt quod aut velit reprehenderit optio sapiente libero doloremque, veritatis rem incidunt. Laudantium, blanditiis minus! Tenetur, neque nam? Quod blanditiis, sed vero nemo architecto quisquam.
                    Cupiditate ullam consectetur neque eum iusto numquam tenetur odit distinctio maxime, doloremque nisi rem quidem in impedit reprehenderit ea, quo tempora recusandae animi molestias sapiente asperiores vitae? Deleniti, excepturi quis.
                    Cum hic necessitatibus magnam dolores. Unde adipisci voluptatibus rem velit error a, corrupti cumque illo, distinctio amet nulla. Mollitia at laboriosam omnis amet in quod ipsum natus ipsa, temporibus debitis.
                    Suscipit possimus quas dolor dolores deserunt et, voluptatem minima animi recusandae sed, accusantium non! Animi, odit! Facere sunt ea obcaecati magnam dolores error dicta mollitia laboriosam, minima debitis iusto doloribus.
                    Corrupti labore quo quas eius enim et rem laboriosam, eaque nam fugit cum animi repellendus veniam odio consequatur suscipit atque assumenda dolore cupiditate hic aliquid dolorem minima vero? Perspiciatis, hic.
                    Iusto laudantium aut aliquam, modi fugit error aspernatur minima vel voluptate accusamus nihil veritatis? Similique incidunt dignissimos nam laborum atque architecto distinctio laudantium. Nulla vero molestiae quia possimus qui dolore.
                    Officia non tempore labore, consequuntur veritatis ullam consequatur delectus, nemo atque porro expedita quos accusamus commodi sunt quibusdam quis laudantium odio dicta neque iure? Explicabo saepe beatae tenetur obcaecati eum!
                    Sapiente itaque libero unde expedita vitae! Suscipit, voluptates! Voluptas sunt nesciunt quasi ut ullam culpa cupiditate perferendis doloribus amet dignissimos distinctio quidem ab illo aut optio illum, sit, dolor ad.
                    Praesentium quod, odio iste accusantium veritatis tempore quis amet alias dolorum est, harum nisi velit fugit illo voluptatem mollitia. Consectetur aut nulla odit repellendus ea necessitatibus culpa obcaecati eveniet impedit?
                    Quod alias aliquam excepturi facilis magnam quos aut molestiae, sit consequuntur asperiores dolorem recusandae iusto ut accusantium, unde delectus. Quas impedit tempora laboriosam, similique ratione doloribus ea nihil recusandae autem.
                    Voluptate recusandae perspiciatis voluptatem sapiente delectus asperiores quod magnam totam similique reiciendis facere, possimus vero et minima ipsa explicabo sed temporibus officia sit molestiae maxime eligendi sint consectetur! Totam, vel.
                    Rerum harum aliquam nobis quas incidunt libero repellat eos soluta iusto, dolore assumenda mollitia corrupti amet atque repellendus reiciendis nisi quisquam tempore. Nobis temporibus repellendus molestiae sequi porro, molestias alias?
                    Labore dolore quis velit corporis, rerum hic distinctio facilis, deleniti ipsa cupiditate, repellat accusantium numquam amet neque vitae recusandae ipsum. Suscipit voluptas architecto reiciendis. Praesentium impedit vero officia sequi omnis?
                    Adipisci, autem iste? Reiciendis quis corporis eos cupiditate earum tempore. Iure aliquam est illo provident, omnis nulla nam cum repellendus voluptatem deserunt, quas voluptatum doloremque labore nemo suscipit sunt! Veritatis?
                    Sint dicta odio dignissimos quia beatae ex ipsam necessitatibus nemo laboriosam voluptates ut, maiores consequatur suscipit id libero animi! Debitis ab harum, commodi illum totam tenetur aspernatur a pariatur ipsam.
                    Saepe iusto autem incidunt error maxime minima eaque temporibus alias accusantium, ut rerum voluptate unde, sapiente id magnam, architecto natus distinctio? Eligendi sapiente quibusdam cum aut at tempore, delectus maiores.
                    Libero ad soluta adipisci necessitatibus facilis tenetur itaque voluptas inventore distinctio aliquid, sequi, id sunt nobis minima consequuntur. Voluptates veniam dolorum accusamus eius nostrum, itaque ducimus earum perspiciatis reprehenderit libero?
                    Quos cupiditate ipsum natus rem labore nobis. A nihil labore, magnam libero nesciunt ex, perspiciatis optio ullam commodi, voluptate sed odio! Commodi, adipisci minus tenetur incidunt sed veritatis est voluptatem.
                    Sunt a itaque dicta magni repellendus dignissimos praesentium eum qui expedita repellat obcaecati, commodi voluptate eveniet alias nulla aut harum quo sapiente reiciendis? Dolorum earum quod voluptatem doloremque quidem necessitatibus?
                    Unde aliquid totam, adipisci ipsum magni fugiat consequatur ratione expedita, nostrum velit nisi accusamus doloribus facere praesentium porro fuga atque, odit ad commodi! Optio, illum vitae? Id maxime nesciunt quis!
                    Nostrum eius beatae vitae, incidunt placeat accusamus suscipit dolorum quod sed necessitatibus dolor error aliquam impedit repudiandae, mollitia ipsum, maiores eligendi quidem cumque omnis iure accusantium. Iste facere quia atque.
                    Cum assumenda magni, id nulla ipsum labore molestiae aut rem quo quos a doloremque enim ratione perspiciatis facilis veniam ex! Labore in, eum rerum mollitia modi iusto sed porro laudantium!
                    Consequuntur qui, expedita perferendis, saepe pariatur sequi accusamus tempora maiores minima est adipisci ratione? Dicta eum aperiam temporibus eaque iusto dolore commodi pariatur ab. Labore, consectetur ullam? Eum, unde aspernatur.
                    Perspiciatis aspernatur obcaecati, eos corporis qui nisi animi at placeat excepturi, dolore molestiae adipisci assumenda fugiat minus illum quod sint veritatis architecto a. Rem, neque voluptas quis laborum qui reiciendis.
                    Eligendi amet illo omnis qui, sapiente beatae explicabo esse corporis commodi ea tenetur placeat enim quidem, vel voluptatum officia? Qui laborum natus laboriosam autem voluptates illum voluptas, quidem aliquam porro?
                    Ratione possimus enim sit exercitationem natus saepe in beatae quis numquam, voluptatum sed ea hic nemo voluptates perspiciatis fuga architecto dolores? Rem delectus eos voluptate, sit dolores ipsam magni fugiat.
                    Modi ducimus perferendis sapiente ea debitis sed cum neque, ipsum, exercitationem dolores recusandae sunt hic et consequuntur sint, esse iste natus. Similique a amet alias consectetur dolor nam quod quibusdam!
                    Velit amet porro ex incidunt tempora est, veritatis numquam maiores saepe sequi quod quam. Provident, nobis voluptates cupiditate ullam a rerum molestiae, ea adipisci omnis quis tenetur laudantium repellendus atque.
                    Obcaecati quas, eos dicta perspiciatis quasi molestiae possimus? Explicabo quod tenetur cumque, aliquam molestiae neque maxime voluptatem sunt iusto eligendi. Porro placeat sapiente asperiores reiciendis quia quisquam inventore minus sed.
                    Aut quo officiis corporis aperiam obcaecati. Sapiente soluta vero atque neque impedit ratione earum quos doloribus, necessitatibus a ipsum cumque iste? Deserunt provident sint voluptatum cum, repellat expedita quibusdam ratione!
                    Modi consectetur nulla non quam nemo, voluptate magnam dolorem veniam voluptatum. Esse eum modi laborum cumque omnis? Sint natus odio cumque! Odio exercitationem quidem consequuntur laborum ipsam officiis fuga ad!
                    Incidunt officiis sequi, temporibus voluptate a, veritatis, nam excepturi magnam molestias quisquam amet repudiandae dolores et eligendi nulla non? Tempora eveniet suscipit ad sint tenetur nulla placeat nihil non quidem?
                    Odit fugit dolorum, saepe deleniti possimus inventore maiores officia repellat praesentium similique a quod sequi mollitia nemo quisquam cum voluptatum eum facere fuga. Quibusdam expedita unde alias, ullam distinctio eligendi.
                    Unde sequi, repellat veritatis soluta reprehenderit quos illum! Hic, maxime esse. Non repellendus, expedita animi ipsum illum, dolorum aperiam quos a incidunt corrupti omnis error reiciendis dignissimos fugiat cupiditate minima.
                    Inventore voluptate itaque voluptatum ipsum placeat beatae tempore accusantium soluta magni, officiis, optio, fugiat earum obcaecati? Laboriosam dignissimos nam alias, sint sunt praesentium reprehenderit pariatur, inventore corrupti modi qui dolore!
                    Inventore eaque hic ex consequuntur porro! Sint aliquam inventore magni dolorum. Nisi iste adipisci mollitia reprehenderit voluptatum nemo, eveniet eum ipsam, omnis veniam quas provident porro quaerat quae, veritatis earum!
                    Excepturi possimus aliquid doloribus magnam sint dolores voluptatem hic? Iste unde aliquid sapiente earum fuga, vitae nisi, inventore ab, ipsa amet pariatur cupiditate asperiores voluptas corporis nemo quis perspiciatis nulla.
                    Nisi ad at suscipit, laudantium vitae itaque aut quo officia, repellat omnis esse id porro fugit magnam nemo? Eius beatae, quaerat reprehenderit ad tempore quo corrupti consequatur repudiandae modi distinctio.
                    Doloremque explicabo voluptatibus autem maiores perferendis, voluptatem, dolorem cupiditate cumque vel accusamus expedita, quas rem. Veniam a quibusdam voluptatem officia ab natus atque consectetur! Deleniti tempore veritatis odio consectetur nulla.
                    Culpa, quasi, nisi atque totam assumenda quis accusamus est magnam voluptates asperiores fugit quia quidem alias doloribus consequuntur mollitia molestias maiores, veniam eum eligendi id iste laboriosam laborum vitae. Officia!
                    Ea dignissimos minima praesentium blanditiis. Libero quod, animi temporibus eaque incidunt consequatur earum minus, eius fugiat facere sed veniam ex placeat voluptatibus harum unde cupiditate. Quaerat sunt odio iste voluptatem.
                    Nisi voluptates velit quia modi, accusantium voluptatum harum laudantium excepturi aliquid! Ad cupiditate facere voluptatum ex in ut omnis corrupti maiores velit odit? Consequatur maxime, laborum quia temporibus iure cumque?
                    Veritatis sit reiciendis porro itaque rem voluptate doloremque architecto, animi soluta necessitatibus harum, possimus similique! Vel, recusandae explicabo eum doloremque perspiciatis culpa laboriosam quia esse, dolore quis voluptas accusamus mollitia.
                    Deleniti id maiores cum quo enim quibusdam reprehenderit necessitatibus tempora fugiat sit, eius repellat quisquam quia deserunt at porro aut ipsa non quod, hic nobis cupiditate minus! Cum, et quam?
                    Sequi doloremque ullam et necessitatibus quo iste eveniet impedit odit maiores molestias quos sint a saepe non, eligendi illum. Alias iusto voluptatem fugiat. Cumque tempore facilis vero. Mollitia, nesciunt cum.
                    Sequi reprehenderit voluptatibus non delectus, fugit facere alias? Alias neque assumenda soluta similique quas dolores deserunt modi sed tempora facere iusto eveniet autem, necessitatibus debitis ea id corrupti, sequi consequuntur.
                    Sint porro provident aperiam cupiditate minima tenetur asperiores inventore. Sunt nam dicta rerum delectus! Ratione totam dolores reprehenderit labore cumque laboriosam, aperiam velit saepe quos inventore sunt ea architecto voluptate.
                    Voluptas recusandae odit atque illo cupiditate voluptate explicabo repellendus dolorem libero aperiam, dolore natus aut? Voluptas numquam, dolorum optio molestiae doloremque fugiat deleniti aperiam ipsa nulla autem, beatae recusandae animi.
                    Quaerat est incidunt impedit? Delectus accusantium optio, vero dignissimos facere sapiente eos itaque soluta molestias, blanditiis magnam quas ut obcaecati, dolore nisi suscipit labore ad atque sed voluptatibus. Dolor, accusamus?
                    Quis veniam id doloremque? Ex adipisci obcaecati laboriosam? Animi accusamus voluptatem expedita quam quibusdam possimus pariatur sit eos omnis, natus placeat impedit fugit architecto sed, consequatur eum molestias quaerat adipisci.
                    Voluptates iure sed consectetur iste ex, quos nobis. Soluta eveniet reiciendis aut ducimus quasi provident alias aliquam animi fugit distinctio dolor iste labore, recusandae laborum porro similique reprehenderit tempora cum?
                    Beatae aliquam asperiores, at soluta nobis commodi blanditiis? Dolore non dignissimos ratione commodi architecto in maiores laboriosam odit aspernatur molestiae dicta minus totam, consequuntur nemo repellat iusto odio incidunt minima?
                    Nobis suscipit est itaque illo et debitis perspiciatis unde sit deserunt quod vel accusamus dignissimos quia doloremque quas totam delectus ex eum ducimus, aspernatur soluta omnis aliquid. Ex, quisquam voluptatem?
                    Accusantium magnam soluta quo labore, dolorem totam impedit saepe earum, ipsam reiciendis fugit temporibus voluptates, quidem animi est blanditiis commodi. Commodi odit numquam in voluptas consequatur facilis ipsam perferendis quisquam?
                    Ipsum adipisci vero voluptatem omnis porro aliquam, repudiandae non, nam quos, placeat unde cumque recusandae et dolore corrupti doloribus? Laborum illum cum minima amet suscipit tempora alias iusto est quibusdam!</Typography>
            </>
        )
    }
    return getServices();
}

export default React.memo(Service);